apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment2
  labels:
    app: demo-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app2
  template:
    metadata:
      labels:
        app: demo-app2
    spec:

      containers:
      - image: gcr.io/rising-minutia-309213/task2image:latest
        name: task2image
        imagePullPolicy: Always
        
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service2
spec:
  selector:
    app: demo-app2
  ports:
    - port: 8096
      targetPort: 8096
     
  type: LoadBalancer
